SELECT TOP (1000) [user_id]
      ,[tc_identity]
      ,[password_hash]
      ,[full_name]
      ,[birth_date]
      ,[gender]
      ,[email]
      ,[city]
      ,[profile_pic]
      ,[created_at]
      ,[plain_password]
  FROM [DiyabetDB].[dbo].[users]
